[package]
name = "vector-graphics"
description = "vector graphics library"
version = "1.1.3"
authors = ["cyaxares <me@siamand.cc>"]
edition = "2018"
repository = "https://github.com/SiamandMaroufi/vector-graphics"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"